# ----- Running on Codespaces ----
# [server]
# maxUploadSize = 2048   # 2 GB
# enableCORS = false
# address = "0.0.0.0"


# ----- Running Locally ----
[server]
maxUploadSize = 2048   # 2 GB
enableCORS = false
address = "localhost"
port = 8501
headless = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
base = "dark"